CREATE VIEW [Integration].[Logs] AS
	SELECT		  LA.[LineageKey]
				, LA.[TableName]
				, LA.[DataLoadStarted]
				, LA.[DataLoadCompleted]
				, LA.[WasSuccessful]
				, SL.[event]
				, SL.[source]
				, SL.[starttime]
				, SL.[endtime]
				, SL.[datacode]
				, SL.[message]
				, EL.[ErrorCode]
				, EL.[ErrorDescription]
				, EL.[FailedConfigurations]
				, EL.[ParametersValues]
	FROM		[Integration].[Lineage] AS LA
	LEFT JOIN	[Integration].[ErrorLog] AS EL ON LA.[LineageKey] = EL.[LineageKey]
	LEFT JOIN	[dbo].[sysssislog] AS SL ON EL.[executionid] = SL.[executionid]
				AND EL.[sourceid] = SL.[sourceid]