CREATE PROCEDURE [Integration].[AddUnknownDate] AS
BEGIN
    SET DATEFIRST 1;
    
	IF NOT EXISTS ( SELECT * FROM [Dimension].[Date] WHERE [DateKey] = 19960101 )
	INSERT [Dimension].[Date] (
			  [DateKey]
            , [AlterDateKey]
            , [DayOfMonth]
            , [DayOfWeek]
            , [DayOfWeekNumber]
            , [DayOfQuarterNumber]
            , [DayOfYearNumber]
            , [Year]
            , [StartOfYear]
            , [EndOfYear]
            , [Quarter]
            , [YearQuarter]
            , [YearQuarterNumber]
            , [StartOfQuarter]
            , [EndOfQuarter]
            , [Month]
            , [Mon]
            , [MonthNumber]
            , [YearMonth]
            , [StartOfMonth]
            , [EndOfMonth]
            , [Week]
            , [IOSWeekNumber]
            , [StartOfWeek]
            , [EndOfWeek]
            , [Holiday]
            , [WorkDayType]
            , [WorkDayHours]
	) SELECT	  [DateKey]
                , [AlterDateKey]
                , [DayOfMonth]
                , [DayOfWeek]
                , [DayOfWeekNumber]
                , [DayOfQuarterNumber]
                , [DayOfYearNumber]
                , [Year]
                , [StartOfYear]
                , [EndOfYear]
                , [Quarter]
                , [YearQuarter]
                , [YearQuarterNumber]
                , [StartOfQuarter]
                , [EndOfQuarter]
                , [Month]
                , [Mon]
                , [MonthNumber]
                , [YearMonth]
                , [StartOfMonth]
                , [EndOfMonth]
                , [Week]
                , [IOSWeekNumber]
                , [StartOfWeek]
                , [EndOfWeek]
                , [Holiday]
                , [WorkDayType]
                , [WorkDayHours] 
	FROM		[Integration].[GenerateDateDimensionColumns] ( DATEFROMPARTS ( 1996, 1, 1 ) )
END