CREATE PROCEDURE [Integration].[AddUnknownDate]
AS BEGIN
    IF NOT EXISTS ( SELECT 1 FROM [Dimension].[Date] WHERE [DateKey] = 19951231 )
    INSERT [Dimension].[Date] (
			[DateKey]
        , [AlterDateKey]
        , [DayOfMonth]
        , [DayOfWeek]
        , [DayOfWeekNumber]
        , [DayOfQuarterNumber]
        , [DayOfYearNumber]
        , [Year]
        , [StartOfYear]
        , [EndOfYear]
        , [Quarter]
        , [YearQuarter]
        , [YearQuarterNumber]
        , [StartOfQuarter]
        , [EndOfQuarter]
        , [Month]
        , [Mon]
        , [MonthNumber]
        , [YearMonth]
        , [StartOfMonth]
        , [EndOfMonth]
        , [Week]
        , [IOSWeekNumber]
        , [StartOfWeek]
        , [EndOfWeek]
        , [Holiday]
        , [WorkDayType]
        , [WorkDayHours]
	) SELECT	  [DateKey]
                , [AlterDateKey]
                , [DayOfMonth]
                , [DayOfWeek]
                , [DayOfWeekNumber]
                , [DayOfQuarterNumber]
                , [DayOfYearNumber]
                , [Year]
                , [StartOfYear]
                , [EndOfYear]
                , [Quarter]
                , [YearQuarter]
                , [YearQuarterNumber]
                , [StartOfQuarter]
                , [EndOfQuarter]
                , [Month]
                , [Mon]
                , [MonthNumber]
                , [YearMonth]
                , [StartOfMonth]
                , [EndOfMonth]
                , [Week]
                , [IOSWeekNumber]
                , [StartOfWeek]
                , [EndOfWeek]
                , [Holiday]
                , [WorkDayType]
                , [WorkDayHours]
		FROM	[Integration].[GenerateDateDimensionColumns] ( 19951231 )
END