CREATE PROCEDURE [Integration].[DropLoadTableOrder]
AS BEGIN
    --BEGIN TRY
    --    BEGIN TRANSACTION
			DROP TABLE IF EXISTS [Integration].[Order];
			DROP PARTITION SCHEME [PS_Load_Order_Data];
			DROP PARTITION SCHEME [PS_Load_Order_Index];
			DROP PARTITION FUNCTION [PF_Load_Order];
  --      COMMIT TRANSACTION;
  --  END TRY
  --  BEGIN CATCH
  --      ROLLBACK TRANSACTION;
  --      DECLARE @Msg AS NVARCHAR(2048) = FORMATMESSAGE(50002, ERROR_NUMBER(), ERROR_LINE(), ERROR_MESSAGE());
		--THROW 50002, @Msg, 1;
  --  END CATCH
END