CREATE TABLE [dbo].[Employee] (
    [EmployeeAlterKey_Source]     BIGINT         NULL,
    [EmployeeAlterKey_Output]     BIGINT         NULL,
    [EmployeeAlterKey_Reason]     NVARCHAR (MAX) NULL,
    [EmployeeAlterKey_Confidence] NVARCHAR (MAX) NULL,
    [EmployeeAlterKey_Status]     NVARCHAR (MAX) NULL,
    [Name_Source]                 NVARCHAR (MAX) NULL,
    [Name_Output]                 NVARCHAR (MAX) NULL,
    [Name_Reason]                 NVARCHAR (MAX) NULL,
    [Name_Confidence]             NVARCHAR (MAX) NULL,
    [Name_Status]                 NVARCHAR (MAX) NULL,
    [Title_Source]                NVARCHAR (MAX) NULL,
    [Title_Output]                NVARCHAR (MAX) NULL,
    [Title_Reason]                NVARCHAR (MAX) NULL,
    [Title_Confidence]            NVARCHAR (MAX) NULL,
    [Title_Status]                NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Source]      NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Output]      NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Reason]      NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Confidence]  NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Status]      NVARCHAR (MAX) NULL,
    [City_Source]                 NVARCHAR (MAX) NULL,
    [City_Output]                 NVARCHAR (MAX) NULL,
    [City_Reason]                 NVARCHAR (MAX) NULL,
    [City_Confidence]             NVARCHAR (MAX) NULL,
    [City_Status]                 NVARCHAR (MAX) NULL,
    [Country_Source]              NVARCHAR (MAX) NULL,
    [Country_Output]              NVARCHAR (MAX) NULL,
    [Country_Reason]              NVARCHAR (MAX) NULL,
    [Country_Confidence]          NVARCHAR (MAX) NULL,
    [Country_Status]              NVARCHAR (MAX) NULL,
    [Record_Status]               NVARCHAR (MAX) NULL
);

