CREATE TABLE [dbo].[NW_Customers](
    [CustomerID_Source]       NVARCHAR(5)       NULL,
    [CustomerID_Output]       NVARCHAR(5)       NULL,
    [CustomerID_Reason]       NVARCHAR(MAX)     NULL,
    [CustomerID_Confidence]   NVARCHAR(100)     NULL,
    [CustomerID_Status]       NVARCHAR(100)     NULL,
    [CompanyName_Source]      NVARCHAR(40)      NULL,
    [CompanyName_Output]      NVARCHAR(40)      NULL,
    [CompanyName_Reason]      NVARCHAR(MAX)     NULL,
    [CompanyName_Confidence]  NVARCHAR(100)     NULL,
    [CompanyName_Status]      NVARCHAR(100)     NULL,
    [ContactName_Source]      NVARCHAR(30)      NULL,
    [ContactName_Output]      NVARCHAR(30)      NULL,
    [ContactName_Reason]      NVARCHAR(MAX)     NULL,
    [ContactName_Confidence]  NVARCHAR(100)     NULL,
    [ContactName_Status]      NVARCHAR(100)     NULL,
    [ContactTitle_Source]     NVARCHAR(30)      NULL,
    [ContactTitle_Output]     NVARCHAR(30)      NULL,
    [ContactTitle_Reason]     NVARCHAR(MAX)     NULL,
    [ContactTitle_Confidence] NVARCHAR(100)     NULL,
    [ContactTitle_Status]     NVARCHAR(100)     NULL,
    [City_Source]             NVARCHAR(15)      NULL,
    [City_Output]             NVARCHAR(15)      NULL,
    [City_Reason]             NVARCHAR(MAX)     NULL,
    [City_Confidence]         NVARCHAR(100)     NULL,
    [City_Status]             NVARCHAR(100)     NULL,
    [Country_Source]          NVARCHAR(15)      NULL,
    [Country_Output]          NVARCHAR(15)      NULL,
    [Country_Reason]          NVARCHAR(MAX)     NULL,
    [Country_Confidence]      NVARCHAR(100)     NULL,
    [Country_Status]          NVARCHAR(100)     NULL,
    [Phone_Source]            NVARCHAR(24)      NULL,
    [Phone_Output]            NVARCHAR(24)      NULL,
    [Phone_Reason]            NVARCHAR(MAX)     NULL,
    [Phone_Confidence]        NVARCHAR(100)     NULL,
    [Phone_Status]            NVARCHAR(100)     NULL,
    [Fax_Source]              NVARCHAR(24)      NULL,
    [Fax_Output]              NVARCHAR(24)      NULL,
    [Fax_Reason]              NVARCHAR(MAX)     NULL,
    [Fax_Confidence]          NVARCHAR(100)     NULL,
    [Fax_Status]              NVARCHAR(100)     NULL,
    [Record Status]           NVARCHAR(100)     NULL,
    [Appended data]           NVARCHAR(MAX)     NULL,
    [Appended data schema]    NVARCHAR(MAX)     NULL
);

