CREATE TABLE [dbo].[NW_Employee] (
    [EmployeeID_Source]          INT            NULL,
    [EmployeeID_Output]          INT            NULL,
    [EmployeeID_Reason]          NVARCHAR (MAX) NULL,
    [EmployeeID_Confidence]      NVARCHAR (MAX) NULL,
    [EmployeeID_Status]          NVARCHAR (MAX) NULL,
    [LastName_Source]            NVARCHAR (20)  NULL,
    [LastName_Output]            NVARCHAR (MAX) NULL,
    [LastName_Reason]            NVARCHAR (MAX) NULL,
    [LastName_Confidence]        NVARCHAR (MAX) NULL,
    [LastName_Status]            NVARCHAR (MAX) NULL,
    [FirstName_Source]           NVARCHAR (20)  NULL,
    [FirstName_Output]           NVARCHAR (MAX) NULL,
    [FirstName_Reason]           NVARCHAR (MAX) NULL,
    [FirstName_Confidence]       NVARCHAR (MAX) NULL,
    [FirstName_Status]           NVARCHAR (MAX) NULL,
    [Title_Source]               NVARCHAR (30)  NULL,
    [Title_Output]               NVARCHAR (MAX) NULL,
    [Title_Reason]               NVARCHAR (MAX) NULL,
    [Title_Confidence]           NVARCHAR (MAX) NULL,
    [Title_Status]               NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Source]     NVARCHAR (10)  NULL,
    [TitleOfCourtesy_Output]     NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Reason]     NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Confidence] NVARCHAR (MAX) NULL,
    [TitleOfCourtesy_Status]     NVARCHAR (MAX) NULL,
    [City_Source]                NVARCHAR (25)  NULL,
    [City_Output]                NVARCHAR (MAX) NULL,
    [City_Reason]                NVARCHAR (MAX) NULL,
    [City_Confidence]            NVARCHAR (MAX) NULL,
    [City_Status]                NVARCHAR (MAX) NULL,
    [Country_Source]             NVARCHAR (25)  NULL,
    [Country_Output]             NVARCHAR (MAX) NULL,
    [Country_Reason]             NVARCHAR (MAX) NULL,
    [Country_Confidence]         NVARCHAR (MAX) NULL,
    [Country_Status]             NVARCHAR (MAX) NULL,
    [Record_Status]              NVARCHAR (MAX) NULL
);

