CREATE VIEW [Reports].[DimDate] AS
	SELECT		  [DateKey]
				, [AlterDateKey]
				, [Year]
				, [YearQuarterNumber]
				, [YearQuarter]
				, [Quarter]
				, [YearMonth]
				, [YearMonthNumber]
				, [Month]
				, [MonthNumber]
				, [DayOfMonth]
				, [DayOfWeekNumber]
				, [DayOfWeek]
				, [WeekNumber]
	
	FROM		[Dimension].[Date]