CREATE VIEW [Reports].[DimDate]
    WITH SCHEMABINDING
AS
	SELECT		  [DateKey]
                , [DayOfMonth]
                , [DayOfWeek]
                , [DayOfWeekNumber]
                , [DayOfQuarterNumber]
                , [DayOfYearNumber]
                , [Year]
                , [StartOfYear]
                , [EndOfYear]
                , [Quarter]
                , [YearQuarter]
                , [YearQuarterNumber]
                , [StartOfQuarter]
                , [EndOfQuarter]
                , [Month]
                , [Mon]
                , [MonthNumber]
                , [YearMonth]
                , [StartOfMonth]
                , [EndOfMonth]
                , [Week]
                , [ISOWeekNumber]
                , [StartOfWeek]
                , [EndOfWeek]
                , [Holiday]
                , [WorkDayType]
                , [WorkDayHours] 
	
	FROM		[Dimension].[Date]
	WITH (NOLOCK);