CREATE PROCEDURE [Landing].[DropPrimaryKeyProducts] AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			ALTER TABLE [Landing].[Products] DROP CONSTRAINT [PK_Landing_Products];
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        DECLARE @Msg AS NVARCHAR(2048) = FORMATMESSAGE(50002, ERROR_NUMBER(), ERROR_LINE(), ERROR_MESSAGE());
		THROW 50002, @Msg, 1;
    END CATCH
END