CREATE PROCEDURE [Landing].[DropPrimaryKeyHolidays] AS
BEGIN
	--BEGIN TRY
	--	BEGIN TRANSACTION
			ALTER TABLE [Landing].[Holidays] DROP CONSTRAINT [PK_Landing_Holidays];
  --      COMMIT TRANSACTION;
  --  END TRY
  --  BEGIN CATCH
  --      ROLLBACK TRANSACTION;
  --      DECLARE @Msg AS NVARCHAR(2048) = FORMATMESSAGE(50002, ERROR_NUMBER(), ERROR_LINE(), ERROR_MESSAGE());
		--THROW 50002, @Msg, 1;
  --  END CATCH
END