USE [NorthwindDW]
GO

IF NOT EXISTS ( SELECT 1 FROM [sys].[sysusers] WHERE [name] = 'SWIFT3\RDLexec' )
	BEGIN
		CREATE USER [SWIFT3\RDLexec] FOR LOGIN [SWIFT3\RDLexec]
			WITH DEFAULT_SCHEMA=[Reports]
	END
GO

IF NOT EXISTS ( SELECT 1 FROM [sys].[sysusers] WHERE [name] = 'SWIFT3\UserBI' )
	BEGIN
		CREATE USER [SWIFT3\UserBI] FOR LOGIN [SWIFT3\UserBI]
			WITH DEFAULT_SCHEMA=[Reports]
	END
GO

ALTER ROLE [dwh_user] ADD MEMBER [SWIFT3\RDLexec]
GO
ALTER ROLE [dwh_user] ADD MEMBER [SWIFT3\UserBI]
GO

USE [DQS_STAGING_DATA]
GO

IF NOT EXISTS ( SELECT 1 FROM [sys].[sysusers] WHERE [name] = 'SWIFT3\RDLexec' )
	BEGIN
		CREATE USER [SWIFT3\RDLexec] FOR LOGIN [SWIFT3\RDLexec]
			WITH DEFAULT_SCHEMA=[dbo]
	END
GO

ALTER ROLE [db_datareader] ADD MEMBER [SWIFT3\RDLexec]
GO

USE [MDS]
GO

IF NOT EXISTS ( SELECT 1 FROM [sys].[sysusers] WHERE [name] = 'SWIFT3\VSTS_AgentService_G39071' )
	BEGIN
		CREATE USER [SWIFT3\VSTS_AgentService_G39071] FOR LOGIN [SWIFT3\VSTS_AgentService_G39071]
			WITH DEFAULT_SCHEMA=[stg]
	END
GO

GRANT SELECT ON SCHEMA::[stg] TO [SWIFT3\VSTS_AgentService_G39071]
GO

GRANT EXECUTE ON SCHEMA::[stg] TO [SWIFT3\VSTS_AgentService_G39071]
GO