USE [NorthwindDW]
GO
IF NOT EXISTS ( SELECT 1 FROM [sys].[sysusers] WHERE [name] = 'SWIFT3\RDLexec' )
	BEGIN
		CREATE USER [SWIFT3\RDLexec] FOR LOGIN [SWIFT3\RDLexec]
			WITH DEFAULT_SCHEMA=[Reports]
	END
GO

IF NOT EXISTS ( SELECT 1 FROM [sys].[sysusers] WHERE [name] = 'SWIFT3\UserBI' )
	BEGIN
		CREATE USER [SWIFT3\UserBI] FOR LOGIN [SWIFT3\UserBI]
			WITH DEFAULT_SCHEMA=[Reports]
	END
GO

ALTER ROLE [dwh_user] ADD MEMBER [SWIFT3\RDLexec]
GO
ALTER ROLE [dwh_user] ADD MEMBER [SWIFT3\UserBI]
GO