USE [NorthwindDW]
GO
CREATE USER [SWIFT3\RDLexec] FOR LOGIN [SWIFT3\RDLexec]
	WITH DEFAULT_SCHEMA=[Reports]
GO
CREATE USER [SWIFT3\UserBI] FOR LOGIN [SWIFT3\UserBI]
	WITH DEFAULT_SCHEMA=[Reports]
GO
ALTER ROLE [dwh_user] ADD MEMBER [SWIFT3\RDLexec]
GO
ALTER ROLE [dwh_user] ADD MEMBER [SWIFT3\UserBI]
GO