"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "SELECT DISTINCT C.[CustomerID], [CompanyName], [ContactName], [ContactTitle], [City], [Country], [Phone], [Fax] FROM [Landing].[Customers] AS C INNER JOIN [Landing].[Orders] AS O ON C.[CustomerID] = O.[CustomerID] AND O.[OrderDate] BETWEEN N'1996-01-01' AND N'1997-12-31'" queryout "C:\Users\ZinukovD\source\repos\Northwind_BI_Solution\IngestData\1997-12-31\Customers.dat" -S "N-MSC-478" -d "NorthwindLanding" -x -c -T

::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Categories]" format nul -f "C:\SSIS\NorthwindBI\IngestData\Categories.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)" -x -c
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Customers]" format nul -f "C:\SSIS\NorthwindBI\IngestData\Customers.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)" -x -c
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Employees]" format nul -f "C:\SSIS\NorthwindBI\IngestData\Employees.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)" -x -c
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Order Details]" format nul -f "C:\SSIS\NorthwindBI\IngestData\Order Details.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)" -x -c
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Orders]" format nul -f "C:\SSIS\NorthwindBI\IngestData\Orders.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)" -x -c
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Products]" format nul -f "C:\SSIS\NorthwindBI\IngestData\Products.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)" -x -c

::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Categories]" out "C:\SSIS\NorthwindBI\IngestData\Categories.dat" -f "C:\SSIS\NorthwindBI\IngestData\Categories.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)"
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Customers]" out "C:\SSIS\NorthwindBI\IngestData\Customers.dat" -f "C:\SSIS\NorthwindBI\IngestData\Customers.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)"
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Employees]" out "C:\SSIS\NorthwindBI\IngestData\Employees.dat" -f "C:\SSIS\NorthwindBI\IngestData\Employees.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)"
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Order Details]" out "C:\SSIS\NorthwindBI\IngestData\Order Details.dat" -f "C:\SSIS\NorthwindBI\IngestData\Order Details.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)"
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Orders]" out "C:\SSIS\NorthwindBI\IngestData\Orders.dat" -f "C:\SSIS\NorthwindBI\IngestData\Orders.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)"
::"%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe" "[dbo].[Products]" out "C:\SSIS\NorthwindBI\IngestData\Products.dat" -f "C:\SSIS\NorthwindBI\IngestData\Products.fmt" -S "SQL.Samorodov.su" -d "Northwind (упрощённая)"
